import tempfile
from unittest import TestCase

import os
from arx_tools.rename_eggnog import *

EGGNOG_CONTENT = """\
## This file was generated by eggNOG-mapper
# version=2.1.2
#query\tseed_ortholog\tevalue\tscore\teggNOG_OGs
OLD_00001\t1234.XYZ\t1e-50\t200.0\tCOG1234@1|root
OLD_00002\t5678.ABC\t1e-30\t150.0\tCOG5678@1|root
OLD_00003\t9999.DEF\t1e-20\t100.0\t-

"""

ROOT = os.path.dirname(os.path.dirname(__file__))
TMPFILE = '/tmp/renamed_eggnog.eggnog'

eggnogs = [
    f'{ROOT}/test-data/prokka-bad/out.emapper.annotations',
    f'{ROOT}/test-data/pgap-bad/out.emapper.annotations',
]


def cleanup():
    if os.path.isfile(TMPFILE):
        os.remove(TMPFILE)


class Test(TestCase):
    def test_detect_locus_tag_prefix(self):
        for eggnog in eggnogs:
            locus_tag_prefix = EggnogFile(file=eggnog).detect_locus_tag_prefix()
            self.assertEqual(locus_tag_prefix, 'tmp_')

    def test_parse_eggnog_date(self):
        for eggnog in eggnogs:
            dt = EggnogFile(file=eggnog).date_str()
            self.assertIs(type(dt), str)

    def test_guess_eggnog_type(self):
        for eggnog in eggnogs:
            eggnog_type = EggnogFile(file=eggnog).custom_annotation_type
            self.assertTrue(eggnog_type.startswith('eggnog'))

    def test_validate_locus_tags(self):
        for eggnog in eggnogs:
            ef = EggnogFile(file=eggnog)
            ef.validate_locus_tags(locus_tag_prefix=None)
            ef.validate_locus_tags(locus_tag_prefix='tmp_')
            with self.assertRaises(AssertionError):
                ef.validate_locus_tags(locus_tag_prefix='xxx_')

    def test_rename(self):
        for eggnog in eggnogs:
            cleanup()
            EggnogFile(file=eggnog).rename(new_locus_tag_prefix='YOLO_', out=TMPFILE, validate=True)
            with open(TMPFILE) as f:
                content = f.read()
            count = content.count('YOLO_')
            self.assertNotIn(member='tmp', container=content)
            self.assertGreater(a=count, b=400)

    def test_cog_extraction(self):
        for eggnog in eggnogs:
            res = EggnogFile(file=eggnog).cog_categories()
            self.assertGreater(len(res), 0)

    def test_rename_by_map(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.emapper.annotations', delete=False) as f:
            f.write(EGGNOG_CONTENT)
            infile = f.name
        outfile = infile + '.out'
        try:
            lt_map = {'OLD_00001': 'NEW_00001', 'OLD_00002': 'NEW_00002', 'OLD_00003': 'NEW_00003'}
            EggnogFile(infile).rename_by_map(out=outfile, lt_map=lt_map, update_path=False)
            with open(outfile) as f:
                result = f.read()
            self.assertIn('NEW_00001', result)
            self.assertIn('NEW_00002', result)
            self.assertIn('NEW_00003', result)
            self.assertNotIn('OLD_', result)
            self.assertIn('## This file was generated', result)
            self.assertIn('# version=2.1.2', result)
            self.assertIn('\n\n', result)  # blank line preserved
        finally:
            os.remove(infile)
            if os.path.isfile(outfile):
                os.remove(outfile)

    def test_rename_by_map_missing_key(self):
        with tempfile.NamedTemporaryFile(mode='w', suffix='.emapper.annotations', delete=False) as f:
            f.write(EGGNOG_CONTENT)
            infile = f.name
        outfile = infile + '.out'
        try:
            lt_map = {'OLD_00001': 'NEW_00001'}  # missing OLD_00002 and OLD_00003
            with self.assertRaises(AssertionError):
                EggnogFile(infile).rename_by_map(out=outfile, lt_map=lt_map)
        finally:
            os.remove(infile)
            if os.path.isfile(outfile):
                os.remove(outfile)

    @classmethod
    def tearDownClass(cls) -> None:
        cleanup()
